### ISSUE TITLE
Allow store sobject with suffix attached to the key

### ISSUE THREAD

**Issue by mezongzi** [osglworks/java-storage#8]
Previously when the sobject is stored there is no suffix:

![image](https://cloud.githubusercontent.com/assets/216930/24993430/a18adb30-2069-11e7-969b-90870b485c36.png)

This request is to allow AAA to store sobject with suffix when possible (e.g. when storing an uploaded file, use the filename's suffix as the sobject's key suffix)

**Comment by greenlaw110** [comment]
fixed in 1.1.0
